import type { AchievementSkin } from "./Achievement";

export const DEFAULT_SKIN_ID = "skin_default";

const S = (s: AchievementSkin) => s;

export const SKIN_DEFS: readonly AchievementSkin[] = [
  S({
    id: "skin_default",
    label: "DEFAULT",
    description: "標準ボール",
    shape: "sphere",
    color: 0xdddddd, metalness: 0.4, roughness: 0.15,
    emissiveColor: 0x000000, emissiveIntensity: 0,
    glowColor: 0xffffff, glowIntensity: 1.0,
    pulseSpeed: 0,
  }),
  S({
    id: "skin_crimson",
    label: "CRIMSON",
    description: "深紅の球体",
    shape: "sphere",
    color: 0xcc2222, metalness: 0.3, roughness: 0.2,
    emissiveColor: 0x330000, emissiveIntensity: 0.3,
    glowColor: 0xff4444, glowIntensity: 1.2,
    pulseSpeed: 0,
  }),
  S({
    id: "skin_gold",
    label: "GOLD",
    description: "輝く黄金",
    shape: "sphere",
    color: 0xffd700, metalness: 0.9, roughness: 0.05,
    emissiveColor: 0x332200, emissiveIntensity: 0.15,
    glowColor: 0xffee44, glowIntensity: 1.5,
    pulseSpeed: 0,
  }),
  S({
    id: "skin_cobalt",
    label: "COBALT",
    description: "コバルトブルー",
    shape: "sphere",
    color: 0x1155cc, metalness: 0.5, roughness: 0.1,
    emissiveColor: 0x001133, emissiveIntensity: 0.2,
    glowColor: 0x3399ff, glowIntensity: 1.3,
    pulseSpeed: 0,
  }),
  S({
    id: "skin_plasma",
    label: "PLASMA",
    description: "脈動するプラズマエネルギー",
    shape: "sphere",
    color: 0x9933ff, metalness: 0.2, roughness: 0.3,
    emissiveColor: 0x220044, emissiveIntensity: 0.5,
    glowColor: 0xcc44ff, glowIntensity: 2.0,
    pulseSpeed: 2.0,
  }),
  S({
    id: "skin_aurora",
    label: "AURORA",
    description: "オーロラの輝き",
    shape: "sphere",
    color: 0x00ffcc, metalness: 0.4, roughness: 0.2,
    emissiveColor: 0x002211, emissiveIntensity: 0.4,
    glowColor: 0x44ffdd, glowIntensity: 1.8,
    pulseSpeed: 1.5,
  }),
  S({
    id: "skin_jade",
    label: "JADE",
    description: "翡翠の原石",
    shape: "sphere",
    color: 0x00aa66, metalness: 0.6, roughness: 0.12,
    emissiveColor: 0x001100, emissiveIntensity: 0.2,
    glowColor: 0x33ffaa, glowIntensity: 1.1,
    pulseSpeed: 0,
  }),
  S({
    id: "skin_chrome",
    label: "CHROME",
    description: "鏡面クローム",
    shape: "sphere",
    color: 0xeeeeee, metalness: 1.0, roughness: 0.02,
    emissiveColor: 0x000000, emissiveIntensity: 0,
    glowColor: 0xffffff, glowIntensity: 0.8,
    pulseSpeed: 0,
  }),
  S({
    id: "skin_fire",
    label: "FIRE",
    description: "燃え盛る炎球",
    shape: "sphere",
    color: 0xff4400, metalness: 0.1, roughness: 0.4,
    emissiveColor: 0x441100, emissiveIntensity: 0.8,
    glowColor: 0xff8800, glowIntensity: 2.5,
    pulseSpeed: 3.0,
  }),
  S({
    id: "skin_cube",
    label: "CUBE",
    description: "球ではなく、キューブ",
    shape: "cube",
    color: 0x888888, metalness: 0.7, roughness: 0.2,
    emissiveColor: 0x000000, emissiveIntensity: 0,
    glowColor: 0xaaaaaa, glowIntensity: 0.9,
    pulseSpeed: 0,
  }),
  S({
    id: "skin_neon",
    label: "NEON",
    description: "暗闇で光るネオン",
    shape: "sphere",
    color: 0x111111, metalness: 0.0, roughness: 0.9,
    emissiveColor: 0x00ff44, emissiveIntensity: 1.0,
    glowColor: 0x00ff88, glowIntensity: 3.0,
    pulseSpeed: 4.0,
  }),
  S({
    id: "skin_obsidian",
    label: "OBSIDIAN",
    description: "伝説の証",
    shape: "spiky",
    color: 0x0a0a12, metalness: 0.95, roughness: 0.01,
    emissiveColor: 0x110022, emissiveIntensity: 0.6,
    glowColor: 0x8844ff, glowIntensity: 2.0,
    pulseSpeed: 1.0,
  }),
  S({
    id: "skin_galaxy",
    label: "GALAXY",
    description: "宇宙の答え",
    shape: "sphere",
    color: 0x1a0a3e, metalness: 0.3, roughness: 0.4,
    emissiveColor: 0x4400aa, emissiveIntensity: 0.7,
    glowColor: 0x8855ff, glowIntensity: 2.2,
    pulseSpeed: 1.2,
  }),
  S({
    id: "skin_rose",
    label: "ROSE",
    description: "意味深な薔薇色",
    shape: "sphere",
    color: 0xff3388, metalness: 0.2, roughness: 0.3,
    emissiveColor: 0x330011, emissiveIntensity: 0.4,
    glowColor: 0xff66aa, glowIntensity: 1.6,
    pulseSpeed: 0,
  }),
  S({
    id: "skin_pi",
    label: "PI",
    description: "円周率の欠片",
    shape: "sphere",
    color: 0x3366ff, metalness: 0.5, roughness: 0.15,
    emissiveColor: 0x001144, emissiveIntensity: 0.3,
    glowColor: 0x4488ff, glowIntensity: 1.4,
    pulseSpeed: 3.14,
  }),
  S({
    id: "skin_jackpot",
    label: "JACKPOT",
    description: "大当たり",
    shape: "spiky",
    color: 0xffcc00, metalness: 0.85, roughness: 0.05,
    emissiveColor: 0x443300, emissiveIntensity: 0.9,
    glowColor: 0xffee00, glowIntensity: 3.0,
    pulseSpeed: 5.0,
  }),
  S({
    id: "skin_invisible",
    label: "INVISIBLE",
    description: "見えない",
    shape: "sphere",
    color: 0x000000, metalness: 0, roughness: 1,
    emissiveColor: 0x000000, emissiveIntensity: 0,
    glowColor: 0x000000, glowIntensity: 0,
    pulseSpeed: 0,
  }),
];

export function getSkinDef(id: string): AchievementSkin {
  return SKIN_DEFS.find((s) => s.id === id) ?? SKIN_DEFS[0];
}
